
{
    'name': 'Tailoring management',
    'version': '16.0.1.0.0',
    'author': 'laxicon solution',
    'website': 'laxicon.in',
    'catagory': 'Tailor',
    'license': 'AGPL-3',
    'Summary': 'Tailoring',
    'description': 'This module is for Tailoring',
    'sequence': '2',
    'depends': ['base', 'mail', 'account', 'l10n_in', 'daily_casebook', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/user_groups.xml',
        'data/sequence.xml',
        'views/tailor_map.xml',
        'views/tailor_shirt.xml',
        'views/tailor_pathani.xml',
        'views/tailor_kurto.xml',
        'views/tailor_chorni.xml',
        'views/tailor_lengho.xml',
        'views/tailor_pent.xml',
        'views/tailor_coti.xml',
        'views/tailor_blazer.xml',
        'views/tailor_menu.xml',
        'views/daily_casebook_view.xml',
        'views/account_payment.xml',
        'views/res_company.xml',
        'views/res_partner_view.xml',
        'reports/report_tailor_receipt.xml',
        'reports/tailor_customer_report.xml',
        'wizard/confirm_wizard_view.xml',
        'wizard/delivery_order_wizard_view.xml',
        'wizard/advance_amount_wizard_view.xml',
        'wizard/refund_deposit_wizard.xml'
    ],
    'assets': {
        'web.report_assets_common': [
                'joli_tailor/static/font_style.scss',
            ],
    },
    'installable': True,
    'application': True,
}
